### ISSUE TITLE
PAPI registers while plugin is disabling

### ISSUE THREAD

**Issue by NicoNekoDev** [Rosstail/Karma#15]
```[23:53:38] [Server thread/INFO]: [Karma] Disabling Karma v1.9.4
[23:53:38] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: karma
[23:53:38] [Server thread/ERROR]: Error occurred while disabling Karma v1.9.4 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.1.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.18.1.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.18.1.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.18.1.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.18.1.jar:git-Paper-175]
	at com.rosstail.karma.Karma.saveData(Karma.java:127) ~[Karma-1.9.4.jar:?]
	at com.rosstail.karma.Karma.onDisable(Karma.java:114) ~[Karma-1.9.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.disablePlugins(CraftServer.java:498) ~[paper-1.18.1.jar:git-Paper-175]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1036) ~[paper-1.18.1.jar:git-Paper-175]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:800) ~[paper-1.18.1.jar:git-Paper-175]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1315) ~[paper-1.18.1.jar:git-Paper-175]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by Rosstail** [comment]
Hi, can you please explain how did it happen, which version of spigot/paper, karma and PAPI ?

Also, did you do `/papi ecloud download karma` ? You must NOT do that. To fix it: 

- Stop your server
- Delete karma in papi/expansions/
- Restart your server

**Comment by NicoNekoDev** [comment]
https://imgur.com/a/uT7YB4u
Happened when I stopped the server.

**Comment by Rosstail** [comment]
I see karma 1.9.4 in the log. Unless this is an error from me, maybe are you using both karma-1.9.4 and 1.9.5 at the same time ?

**Comment by NicoNekoDev** [comment]
> I see karma 1.9.4 in the log. Unless this is an error from me, maybe are you using both karma-1.9.4 and 1.9.5 at the same time ?

nope
![image](https://user-images.githubusercontent.com/13527191/151255426-0ddc6728-2cc2-4f04-bc38-f38d6b062fe1.png)

**Comment by Rosstail** [comment]
Really weird. How many players are connected when the server stops ?

**Comment by NicoNekoDev** [comment]
5 players.

**Comment by Rosstail** [comment]
Hi there, I think you should try the 1.9.7 I have just uploaded on Spigot, it may fix your problem.

I forgot to ask if your datas was saved on local files. If yes, it might be the source of the problem and the reason why I didn't see it.

Link: https://www.spigotmc.org/resources/karma.76077/update?update=443192

**Comment by NicoNekoDev** [comment]
Yes, I'm using the local files. It fixed now.
The error probably occurred because I'm using the Autorestart plugin and it's the only way I trust my server to close. It kicks all players and probability something is getting the placeholder for karma when the players get kicked and the plugin unloads.

**Comment by Rosstail** [comment]
In fact, the problem was caused because I started a Task, which is not allowed when the server closes. So I just directly do the save. So I think your plugin has nothing to do with it.
Have fun !
